export default {
  common: {
    homeTitle: "Happy Work",
    // home

    goToDashboard: "الذهاب إلى لوحة التحكم",
    hero1: "",
    hero2: "",
    SignUp: "اشتراك",
    // dashboard
    dashboard: "لوحة التحكم",
    merchants: "التجار",

    websites: "مواقع الويب",
    environments: "البيئات",
    transactions: "المعاملات",
    profile: "الملف الشخصي",
    creationDate: "تاريخ الإنشاء",
    // display merchant
    displayMerchantTitle: "اختر التاجر",
    dialogCancel: "إلغاء",
    dialogAgree: "موافق",
    delete: "حذف",
    edit: "تعديل",
    firstName: "الاسم",
    lastName: "اللقب",
    email: "البريد الإلكتروني",
    password: "كلمه السر",
    address: "العنوان",
    phoneNumber: "رقم الهاتف",
    currency: "العملة",
    submit: "إرسال",
    country: "البلد",
    status: "الحالة",
    actions: "الإجراءات",
    id: "المعرف",
    viewMerchant: "الذهاب إلى التاجر",
    merchantAlertTitle: "تنبيه",
    merchantAlertContent: "هل تريد حذف هذا التاجر؟",
    // merchant form
    merchantFormEnabled: "مفعل",
    merchantFormDisabled: "غير مفعل",
    merchantFormBlocked: "محظور",
    addNewMerchant: "أضف تاجر جديد",
    // Global Form validation
    emailReq: " الرجاء إدخال البريد الالكتروني ",
    emailValid: "الرجاء إدخال بريد إلكتروني صالح !",
    phonenotValid: "رقم الهاتف غير صالح",
    phoneRequired: " الرجاء إدخال رقم الهاتف",
    lastnemaRequired: "الرجاء إدخال اسم عائلتك",
    lastnameMincaracter: "3 أحرف على الأقل!",
    firstnameRequired: "الرجاء إدخال الاسم",
    firstnameMincaracter: "3 أحرف على الأقل!",
    addressRequired: "الرجاء إدخال العنوان",
    passwordRequired: "الرجاء إدخال كلمة سر",
    currencyRequired: "الرجاء إختيار العملة",
    statusRequired: "الرجاء تحديد الحالة",
    passwordPlaceholder: "أدخل كلمة السر",
    addressPlaceholder: "أدخل عنوانك",
    phonePlaceholder: "أدخل هاتفك",
    firstnamePlaceholder: "أدخل أسمك",
    lastnamePlaceholder: "ادخل اسم عائلتك",
    emailPlaceholder: "أدخل بريدك الإلكتروني",
    passwordMincaracter: " 5 أحرف على الأقل! ",
    websitenameRequired: "* required website name",
    websiteDescRequired: "* required website description",
    websiteUrlRequired: "* required  website url",
    websiteCommisionRequired: "* required website commision",
    successUrlRequired: "* required  website success url",
    failUrlRequired: "* required website failed url",
    notificationUrlRequired: "* required website url notifiction",
    paymentMethodsRequired: "* required website payment method(s)",
    websitename: "enter website name",
    url: "website url",
    name: "website name",
    websiteUrl: "enter website url",
    websiteDescription: "enter website description",
    methods: "website methods",
    ADD_WEBSITE: "add website",
    websiteFailUrl: "enter website failed url",
    websiteSuccessUrl: "enter website success url",
    websiteNotificationUrl: "enter website notification url",
    NotificationUrl: "notification url",
    websiteFormPaypal: "paypal",
    websiteFormCheckout: "checkout",
    websiteFormSobflous: "sobflous",
    websiteFormGpgcheckout: "gpg checkout",
    NA: "غير متاح",
    paymentMethod: "طريقة الدفع",
    Name: "الاسم",
    filterByWebsite: "فلترة حسب المواقع",
    filterByStatus: "فلترة حسب الحالة",
    filterByMethods: "فلترة حسب طرق الدفع",
    // withdraw page
    goBack: "العودة الى الصفحة الرئيسية",
    tnd: "دينار",
    errorMinOneTND: "الرجاء إدخال قيمة بالدينار بحد أدنى 1 دينار تونسي!",
    withdrawFrom: "سحب إلى",
    confirmWithdraw: "تأكيد طلب السحب:",
    confirmWithdrawContent: "هل توافق على سحب مبلغ {amount} دينار من صُب فلوس؟",
    withdraw: "طلب سحب",
    amount: "المبلغ",
    active: "نشط",
    inactive: "غير نشط",
    report: "تقرير",
    transactionsCount: "عدد المعاملات",
    chartTitle: "مخطط المعاملات حسب التاريخ",
    loadingCsv: "تحميل ملف csv ...",
    exportBtn: "تصدير CSV",
    filterByDate: "فلترة حسب التاريخ",
    resetFilters: "إعادة تعيين الفلاتر",
    all: "جميع النتائج",
    transactionId: "المعرف",
    close: "أغلق",
  },
};
