export default {
  common: {
    homeTitle: "Happy Work",
    // home
    goToDashboard: "Go to Dashboard",
    hero1: "Happy Work",
    hero2: "Happy Work ....",
    SignUp: "Sign up",
    // dashboard
    dashboard: "Dashboard",
    merchants: "Merchants",
    websites: "Websites",
    environments: "Environments",
    transactions: "Transactions",
    transactionId: "Transaction ID",
    profile: "Profile",
    // display merchant
    displayMerchantTitle: "Choose a Merchant",
    dialogCancel: "Cancel",
    dialogAgree: "Agree",
    delete: "Delete",
    edit: "Edit",
    firstName: "First Name",
    lastName: "Last name",
    email: "Email",
    password: "Password",
    address: "Address",
    phoneNumber: "Phone Number",
    currency: "Currency",
    submit: "Submit",
    country: "Country",
    status: "Status",
    actions: "Actions",
    id: "ID",
    viewMerchant: "View Merchant",
    merchantAlertTitle: "Alert",
    merchantAlertContent: "Do you want to delete this merchant ?",
    // merchant form
    merchantFormEnabled: "enabled",
    merchantFormDisabled: "disabled",
    merchantFormBlocked: "blocked",
    addNewMerchant: "Add New Merchant",
    // Global Form validation
    emailReq: "* email is required",
    emailValid: "please Enter valid email",
    phonenotValid: "please enter a valid phone number",
    phoneRequired: "* phone number is required",
    lastnemaRequired: "* last name is required",
    lastnameMincaracter: "* 3 characters at least !",
    firstnameRequired: "* first name is required",
    firstnameMincaracter: "* 3 characters at least !",
    addressRequired: "* address is required",
    passwordRequired: "* password is required",
    currencyRequired: "* currency is required",
    statusRequired: "* status is required",
    passwordPlaceholder: "enter your password",
    addressPlaceholder: "enter your address",
    phonePlaceholder: "enter your phone number",
    firstnamePlaceholder: "enter your fisrt name",
    lastnamePlaceholder: "enter your last name",
    emailPlaceholder: "enter your email",
    passwordMincaracter: "* 5 characters at least !",
    websitenameRequired: "* required website name",
    websiteDescRequired: "* required website description",
    websiteUrlRequired: "* required  website url",
    websiteCommisionRequired: "* required website commision",
    successUrlRequired: "* required  website success url",
    failUrlRequired: "* required website failed url",
    notificationUrlRequired: "* required website url notifiction",
    paymentMethodsRequired: "* required website payment method(s)",
    websitename: "enter website name",
    url: "website url",
    name: "website name",
    commission: "Commission",
    more: "More Info",
    description: "description",
    websiteUrl: "enter website url",
    websiteDescription: "enter website description",
    methods: "Payment Methods",
    ADD_WEBSITE: "add website",
    UPDATE_WEBSITE: "update website",
    websiteFailUrl: "enter website failed url",
    websiteSuccessUrl: "enter website success url",
    websiteNotificationUrl: "enter website notification url",
    NotificationUrl: "Notification url",
    websiteFormPaypal: "paypal",
    websiteFormCheckout: "checkout",
    websiteFormSobflous: "sobflous",
    websiteFormGpgcheckout: "gpg checkout",
    successUrl: "Success Url",
    FailUrl: "Fail Url",
    vat: "VAT",
    creationDate: "creation Date",
    filterByDate: "Date",
    resetFilters: "Reset",
    update: "update",
    amount: "amount",
    website: "website",
    countryRequired: "country is required",
    NA: "N/A",
    paymentMethod: "Method",
    Name: "Name",
    filterByWebsite: "Websites",
    filterByStatus: "Status",
    filterByMethods: "Payment Methods",
    // withdraw page
    goBack: "Go Back",
    tnd: "TND",
    errorMinOneTND: "Please enter a value in Dinars with minimum of 1 TND !",
    withdrawFrom: "Withdraw from",
    confirmWithdraw: "Confirm withdrawal request :",
    confirmWithdrawContent: "Agree to withdraw {amount} TND from sobflous ?",
    withdraw: "withdraw",
    active: "Active",
    inactive: "Inactive",
    report: "Report",
    transactionsCount: "Transactions count",
    chartTitle: "Transactions chart by date",
    loadingCsv: "Loading csv...",
    exportBtn: "Export CSV",
    all: "All",
    close: "Close",
  },
};

// {f("homeTitle")}
